baseurl = "/"
languageCode = "en-us"
title = "John Palowitch Stats/ML"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "CCME"
    url = "/ccme/"
    weight = 2
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 4
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 5
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "Homepage of a data scientist. Links/papers/code/posts."
    footer = "&copy; [John Palowitch](https://stats.johnpalowitch.com) 2018 | [Github](https://github.com/jpalowitch) | [Twitter](https://twitter.com/JohnPalowitch)"

  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
